export const COUNTRY_APPLY_ROUTES = {
  Armenia: "ArmeniaApplyScreen",
  Azerbaijan: "AzerbaijanApplyScreen",
  Combodia: "CombodiaApplyScreen",
  Egypt: "EgyptApplyScreen",
  Kenya: "KenyaApplyScreen",
  Morocco: "MoroccoApplyScreen",
  Qatar: "QatarApplyScreen",
  Russia: "RussiaApplyScreen",
  Vietnam: "VietnamApplyScreen",
  Singapore: "SingaporeApplyScreen",
  "Hong Kong": "HongKongApplyScreen",
  "Sri-lanka": "SriLankaApplyScreen",
  Maldives: "MaldivesApplyScreen",
  Malaysia: "MalaysiaApplyScreen",
  Thailand: "ThailandApplyScreen",
  Mauritius: "MauritiusApplyScreen",
};
