export const COUNTRY_APPLY_ROUTES = {
  Vietnam: "VietnamApplyScreen",
  Singapore: "SingaporeApplyScreen",
  "Hong Kong": "HongKongApplyScreen",
  "Sri-lanka": "SriLankaApplyScreen",
  Maldives: "MaldivesApplyScreen",
  Malaysia: "MalaysiaApplyScreen",
  Thailand: "ThailandApplyScreen",
  Mauritius: "MauritiusApplyScreen",
  Japan: "JapanApplyScreen",
  Egypt: "EgyptApplyScreen",
  Morocco: "MoroccoApplyScreen",
  Armenia: "ArmeniaApplyScreen",
  Azerbaijan: "AzerbaijanApplyScreen",
  Combodia: "CombodiaApplyScreen",
  Kenya: "KenyaApplyScreen",
  Russia: "RussiaApplyScreen",
  Qatar: "QatarApplyScreen",
  Georgia: "GeorgiaApplyScreen",
  Cuba: "CubaApplyScreen",
  Bhutan: "BhutanApplyScreen",
  DEFAULT: "GenericApplyScreen",
};
