export const COUNTRY_ISO_MAP = {
  Vietnam: "VN",
  Singapore: "SG",
  "South Korea": "KR",
  Indonesia: "ID",
  "Hong Kong": "HK",
  Combodia: "KH",
  "Sri-lanka": "LK",
  Philippines: "PH",
  Uzbekistan: "UZ",
  Armenia: "AM",
  Russia: "RU",
  France: "FR",
  Italy: "IT",
  USA: "US",
  Sweden: "SE",
  Qatar: "QA",
  Romania: "RO",
  Uganda: "UG",
  Uk: "GB",
  Poland: "PL",
  Portugal: "PT",
  Norway: "NO",
  Nigeria: "NG",
  Netherland: "NL",
  Monoglia: "MN",
  Maldives: "MV",
  Malawi: "MW",
  Liechtenstein: "LI",
  Lebanon: "LB",
  Finland: "FI",
  Colombia: "CO",
  Australia: "AU",
  Austria: "AT",
  Bulgaria: "BG",
  Malaysia: "MY",
  Japan: "JP",
  Thailand: "TH",
  Belgium: "BE",
  Croatia: "HR",
  Czechia: "CZ",
  Denmark: "DK",
  Estonia: "EE",
  Germany: "DE",
  Greece: "GR",
  Hungary: "HU",
  Iceland: "IS",
  Latvia: "LV",
  Lithuania: "LT",
  Luxembourg: "LU",
  Malta: "MT",
  Switzerland: "CH",
  Cyprus: "CY",
  Bhutan: "BT",
  Nepal: "NP",
  Azerbaijan: "AZ",
  Egypt: "EG",
  Kenya: "KE",
  Mauritius: "MU",
  Morocco: "MA",
  "New Zealand": "NZ",
  Oman: "OM",
  Turkey: "TR",
  Ukraine: "UA",
  Georgia: "GE",
  China: "CN",
  Canada: "CA",
  Ireland: "IE",
  Spain: "ES",
  Slovakia: "sk",
  Slovenia: "SI",
  Jamaica: "JM",
  Fiji: "FJ",
  Micronesia: "FM",
  "North Korea": "KP",
  "British Virgin Islands": "VG",
  Barbados: "BB",
  "Cook Islands": "CK",
  "El Salvador": "SV",
  Montserrat: "MS",
  "Trinidad & Tobago": "TT",
  Dominica: "DM",
  Senegal: "SN",
  Réunion: "RE",
  "St. Kitts & Nevis": "KN",
  "St. Vincent & Grenadines": "VC",
  Niue: "NU",
  Haiti: "HT",
  Gambia: "GM",
};
export const getFlagEmoji = (countryName) => {
  const iso = COUNTRY_ISO_MAP[countryName];

  if (!iso) return "🏳️";

  return iso
    .toUpperCase()
    .replace(/./g, char =>
      String.fromCodePoint(127397 + char.charCodeAt())
    );
};